### ISSUE TITLE
Question about training agent

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [datamllab/Policy-GNN#4]
Hello, 

It's a very nice paper and interesting idea.
After reading your basic version code, I have one question about how do you train the agent?
![image](https://user-images.githubusercontent.com/17181332/90658345-c2605200-e243-11ea-95c6-2b9ab4a6b98f.png)
The obtained loss didn't been used after? Thus, it seems you never train the agent but only random draw?

**Comment by lhenry15** [comment]
Hi,

<img width="629" alt="Screen Shot 2020-08-19 at 11 09 34 AM" src="https://user-images.githubusercontent.com/6646890/90661200-852c9d80-e20c-11ea-9378-29e65880507d.png">

The agent ls learned from the environment, if you look into the learn function of the agent, it is connected to the environment. During each timestep, the agent first interacts with the environment using current policy to obtain the trajectories. 

<img width="546" alt="Screen Shot 2020-08-19 at 11 13 23 AM" src="https://user-images.githubusercontent.com/6646890/90661599-0126e580-e20d-11ea-8533-545d867e9b86.png">
Then, the trajectories will be stored into a replay buffer (line 186), after storing the trajectories, we then call agent.train() to sample a batch of experiences and update the Q-network.

**Comment by zhiqiangzhongddu** [comment]
Thanks, much more clear.
