### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [datamllab/Policy-GNN#6]
There should exist an error in current version:
![image](https://user-images.githubusercontent.com/17181332/91299803-83ca1a80-e7a2-11ea-8184-44e6802ab5eb.png)
I guess it should be "A[a] += (1.0 - epsilon)" according to my understandings.

**Comment by lhenry15** [comment]
Thank you for pointing out! We will update this in the next version.

**Comment by zhiqiangzhongddu** [comment]
You are welcome.
Looking forward to the final complete version.
