### ISSUE TITLE
Code in train_*.py

### ISSUE THREAD

**Issue by Unkrible** [datamllab/Policy-GNN#8]
Hello, I have read your paper on KDD2020 and the code recently, it is an interesting work.
Congratulations!
But I have some problems about the code.

In train_*.py scripts, line 37~39 is:
```
if val_acc > last_val: # check whether gain improvement on validation set
        best_policy = deepcopy(agent) # save the best policy
last_val = val_acc 
```

Because each time compare `val_acc` with the previous one `last_val`, you may just get a better strategy than the previous one instead of the optimal one.
For example in the sequence of val_acc `[0.9, 0.8, 0.1, 0.2]`, the final `best_policy` just gets 0.2 val_acc because its acc is higher than the previous one 0.1

Maybe the code should be 
```
if val_acc > last_val: # check whether gain improvement on validation set
        best_policy = deepcopy(agent) # save the best policy
        last_val = val_acc 
```
to get the optimal policy

**Comment by lhenry15** [comment]
Thank you for the suggestion, I will take a try on this and update the code once I found some more tricks to stabilize the current version of the framework.
